version: '3.3'
services:
    mailautoconf:
        container_name: mailautoconf-pod
        ports:
            - '8010:8010'
        volumes:
            - './config:/mailautoconf/config'
        image: pswilde/mailautoconf
